---

name: Compile LaTex to PDF

on: [push]
  
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v2.1.0
        with:
          format: pdf
          filename: resume.tex

      - name: Upload PDF document
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: resume.pdf
