---

name: Compile resume from LaTex to PDF and commit the output file

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.pdf'
      - '**.md'
permissions:
  contents: write
  
jobs:
  compile:
    name: Compile LaTex to MD and PDF
    runs-on: ubuntu-latest
    steps:

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Run pandoc
        run: pandoc --version
    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create output folder
        run: mkdir out
    
      - name: Generate MD document
        run: pandoc --output=out/README.md resume.tex

      - name: Generate PDF document
        run: pandoc --output=out/resume.pdf resume.tex

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: out

  commit:
    name: Add and commit to current repo
    runs-on: ubuntu-latest
    needs: compile
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: resume
        
    - name: Add and commit to main
      run: | 
        git config --global user.name 'dfigueiredo31'
        git config --global user.email 'd.figueiredo@outlook.pt'
        git add .
        git commit -m "Updated resume"
        git push
