---

name: Compile resume from src/resume.yml

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/main.yml'
      - 'src/resume.yml'
      - 'templates/*'

permissions:
  contents: write
  
jobs:
  compile_md:
    name: Compile resume to README.md
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Generate md document (README.md)
       uses: docker://pandoc/extra
       with:
          args: src/resume.yml --template=templates/md_template.md --write=gfm --wrap=none --output=README.md

     - name: Commit README.md
       run: | 
          git config --global user.name 'dfigueiredo31'
          git config --global user.email 'd.figueiredo@outlook.pt'
          git add .
          git commit -m "Update README.md"
          git push

  release_pdf:
    name: Compile resume to PDF
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate PDF document
        uses: docker://pandoc/extra
        with:
          args: src/resume.yml --template=templates/pdf_template.tex --output=david_figueiredo_net_dev_cv.pdf

      - name: Release generated PDF
        uses: ncipollo/release-action@v1
        with:
          artifacts: david_figueiredo_net_dev_cv.pdf
          artifactContentType: application/pdf
          tag: latest
          name: Latest version
