---

name: Compile resume from src/resume.yml

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/main.yml'
      - 'src/resume.yml'
      - 'templates/*'

permissions:
  contents: write
  
jobs:
  compile:
    name: Compile resume source to MD and PDF
    runs-on: ubuntu-latest
    container: pandoc/extra
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate PDF document
        uses: docker://pandoc/extra
        with:
          args: src/resume.yml --template=templates/pdf_template.tex --output=david_figueiredo_net_dev_cv.pdf

      - name: Release generated PDF
        uses: ncipollo/release-action@v1
        with:
          artifacts: david_figueiredo_net_dev_cv.pdf
          artifactContentType: application/pdf
          tag: latest
          name: Latest version

      - name: Generate md document (README.md)
        uses: docker://pandoc/extra
        with:
          args: src/resume.yml --template=templates/md_template.md --write=gfm --wrap=none --output=README.md

      - name: Commit README.md
        run: | 
          git config --global user.name 'dfigueiredo31'
          git config --global user.email 'd.figueiredo@outlook.pt'
          git add README.md
          git commit -m "Compiled a new version of the resume"
          git push
