---

name: Compile resume from README.md file

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/main.yml'
      - 'template/template.tex'
      - 'README.md'
permissions:
  contents: write
  
jobs:
  compile:
    name: Compile LaTex to MD and PDF
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate PDF document
        uses: docker://pandoc/extra
        with:
          args: README.md --metadata-file=template/metadata.yml --template=template/template.tex -o resume.pdf

      - name: Generate LaTex document (for manual editing)
        uses: docker://pandoc/latex
        with:
          args: README.md --metadata-file=template/metadata.yml --template=template/template.tex -o resume.tex

      - name: Create output dir
        run: mkdir -p output/out

      - name: Move resulting files to output
        run: mv resume.tex resume.pdf output/out

      - name: Upload TEX to artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: output/out/*

  commit:
    name: Add and commit artifacts to repo
    runs-on: ubuntu-latest
    needs: compile
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: resume
    
    - shell: bash
      run: ls /home/runner/work/dfigueiredo31/dfigueiredo31
    
    # - name: Add and commit to main
    #   run: | 
    #     git config --global user.name 'dfigueiredo31'
    #     git config --global user.email 'd.figueiredo@outlook.pt'
    #     git add .
    #     git commit -m "Updated resume"
    #     git push
