---

name: Compile resume from LaTex to PDF and commit the output file

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.pdf'
permissions:
  contents: write
  
jobs:
  compile:
    name: Compile LaTex to PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v2.1.0
        with:
          format: md
          filename: resume.tex

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: resume.md

  commit:
    name: Add and commit to current repo
    runs-on: ubuntu-latest
    needs: compile
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: resume
        
    - name: Add and commit to main
      run: | 
        git config --global user.name 'dfigueiredo31'
        git config --global user.email 'd.figueiredo@outlook.pt'
        git add resume.pdf
        git commit -m "Updated resume"
        git push
